### ISSUE TITLE
Script não roda: IndexError: list index out of range

### ISSUE THREAD

**Issue by renatorabelo** [turicas/salarios-magistrados#1]
Traceback (most recent call last):
  File "salarios_magistrados.py", line 196, in <module>
    main()
  File "salarios_magistrados.py", line 192, in main
    export_csv(result, output)
  File "salarios_magistrados.py", line 138, in export_csv
    writer = csv.DictWriter(fobj, fieldnames=data[0].keys())
IndexError: list index out of range

**Comment by turicas** [comment]
Se você instalou corretamente todas as dependências e sua conexão à Internet está funcionando, então o script deveria rodar. Se deu erro nesse ponto é porque provavelmente deu erro antes também (talvez por falta de alguma dependência). Sem colar a saída completa não consigo te ajudar.
