### ISSUE TITLE
erro ao executar script Ubuntu 16.04

### ISSUE THREAD

**Issue by ramonpsilva** [turicas/salarios-magistrados#10]
Olá.
Esta é a mensagem de erro ao executar o script no Ubuntu 16.04 (python 3.5).

ramon@ramon:~/git/salarios-magistrados$ python3 salarios_magistrados.py
  File "salarios_magistrados.py", line 162
    rows.export_to_csv(links, output_path / f'links-{today}.csv')
                                                               ^
SyntaxError: invalid syntax

Muito obrigado por seu trabalho!

**Comment by turicas** [comment]
O script funciona a partir de Python 3.6, [como diz o README](https://github.com/turicas/salarios-magistrados#rodando). Você está usando 3.5.
