### ISSUE TITLE
Github Page

### ISSUE THREAD

**Issue by nicholasess** [turicas/salarios-magistrados#11]
Olá @turicas gostei muito da iniciativa.
Que tal criar uma gh page com os dados estruturados? Não tenho conhecimento em python, então a ideia é gerar um json para consumir.

**Comment by turicas** [comment]
Fala, @nicholasess, tudo bem?
Gostei da ideia! Mas no momento não tenho tempo para implementá-la. Se você puder/quiser fazer, o pull request será muito bem-vindo. :)
Sugiro criar uma interface em HTML que faz o download do JSON e então mostra os dados.
Tendo o arquivo CSV gerado pelo script fica fácil converter pra JSON com o seguinte comando:

```bash
rows convert output/salarios-magistrados-2018-02-05.csv output/salarios-magistrados-2018-02-05.json
```

(necessita ter executado `pip install rows[cli]` para ter esse comando instalado).

**Comment by nicholasess** [comment]
@turicas obrigado pelo feedback
Mandarei no fds
abraços!

**Comment by nicholasess** [comment]
@turicas tentei executar, mas deu o seguinte erro:
```
$ python salarios_magistrados.py
File "salarios_magistrados.py", line 51
SyntaxError: Non-ASCII character '\xc3' in file salarios_magistrados.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by turicas** [comment]
@nicholasess você precisa usar Python 3.6, como diz no README.

**Comment by turicas** [comment]
Vamos usar apenas o Brasil.IO para liberar esses dados, uma página estática no GitHub Pages não será necessária.
