### ISSUE TITLE
Inconsistência no SQLite?

### ISSUE THREAD

**Issue by belisards** [turicas/salarios-magistrados#15]
Com o arquivo _salarios-magistrados-2018-03-05_ parece ter um registro com erro de importação.

Encontrei com esta query:
`select nome, sum(total_de_rendimentos) as v from table1 group by nome order by v desc;`

E todo este valor vem deste registro:
`select * from table1 where nome = '0';`

O arquivo original parece normal

http://www.cnj.jus.br/files/conteudo/arquivo/2018/02/42ed31339fa078281424080592f96e49.xls

**Comment by turicas** [comment]
Eu pensei que já tivesse corrigido esse problema - em geral acontece em tribunais que colocam uma soma no final da tabela.
Fiz alguns ajustes, acabei de rodar e [os novos dados](https://drive.google.com/drive/u/0/folders/1vvHyEOikiVXIIcrZzWkw9J48Wy_nDqKV) não possuem esse problema.
