### ISSUE TITLE
Erro na execução do script.

### ISSUE THREAD

**Issue by danpos** [turicas/salarios-magistrados#7]
> python salarios_magistrados.py 
>   File "salarios_magistrados.py", line 163
>     rows.export_to_csv(links, output_path / f'links-{today}.csv')
>                                                                ^
> SyntaxError: invalid syntax

Executando o script no Ubuntu 16.04 x64 com o Python 3.5.2.

**Comment by turicas** [comment]
O script necessita de Python 3.6+ para rodar, como [consta no README](https://github.com/turicas/salarios-magistrados#rodando).
