### ISSUE TITLE
Erro na execução: module 'rows' has no attribute 'import_from_xpath'

### ISSUE THREAD

**Issue by danpos** [turicas/salarios-magistrados#8]
Após ter instalado o python 3.6 e demais dependências, tentei executar o script, mas ocorreu o seguinte erro:

> Traceback (most recent call last):
>   File "salarios_magistrados.py", line 197, in <module>
>     main()
>   File "salarios_magistrados.py", line 162, in main
>     links = get_links(date=today)
>   File "salarios_magistrados.py", line 42, in get_links
>     table = rows.import_from_xpath(
> AttributeError: module 'rows' has no attribute 'import_from_xpath'

**Comment by turicas** [comment]
Provavelmente você não instalou o módulo lxml ou está usando uma versão antiga da rows. Tente executar:
```bash
pip install -U rows lxml
```
